AHBC_DOTNET_MAY_2021/IntroToApis/Models/ErrorViewModel.cs
using System;

namespace IntroToApis.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AHBC_DOTNET_MAY_2021/IntroToApis/Models/StarWarsPeopleResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace IntroToApis.Models
{

    public class StarWarsPeopleResponse
    {
        public int Count { get; set; }
        public string Next { get; set; }
        public object Previous { get; set; }

        [JsonPropertyName("results")]
        public List<StarsWarsPerson> StarWarsPeople { get; set; }
    }

    public class StarsWarsPerson
    {
        public string Name { get; set; }
        public string Height { get; set; }
        public string mass { get; set; }
        public string hair_color { get; set; }
        public string skin_color { get; set; }
        public string eye_color { get; set; }
        public string birth_year { get; set; }
        public string gender { get; set; }
        public string homeworld { get; set; }
        public string[] films { get; set; }
        public string[] species { get; set; }
        public string[] vehicles { get; set; }
        public string[] starships { get; set; }
        public DateTime created { get; set; }
        public DateTime edited { get; set; }
        public string url { get; set; }
    }

}

AHBC_DOTNET_MAY_2021/IntroToApis/Models/ToolsResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IntroToApis.Models
{
    public class ToolsResponseModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Quanity { get; set; }

        public double Price { get; set; }
    }
}

AHBC_DOTNET_MAY_2021/IntroToApis/Controllers/HomeController.cs
using IntroToApis.Models;
using IntroToApis.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IntroToApis.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AHBC_DOTNET_MAY_2021/IntroToApis/Controllers/StarWarsController.cs
using IntroToApis.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace IntroToApis.Controllers
{
    public class StarWarsController : Controller
    {
        private readonly IStarWarsClient _starsWarsClient;

        public StarWarsController(IStarWarsClient starsWarsClient)
        {
            _starsWarsClient = starsWarsClient;
        }

        public async Task<IActionResult> Index()
        {
            var peopleModel = await _starsWarsClient.GetPeopleAsync();
            return View(peopleModel.results);
        }
    }
}

AHBC_DOTNET_MAY_2021/IntroToApis/Controllers/ToolsController.cs
using IntroToApis.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IntroToApis.Controllers
{
    public class ToolsController : Controller
    {
        private readonly ToolsClient _starsWarsClient;

        
        public ToolsController(ToolsClient starsWarsClient)
        {
            _starsWarsClient = starsWarsClient;
        }

        public async Task<IActionResult> Index()
        {
            var thing = await _starsWarsClient.GetToolsAsync();
            return View(thing);
        }
    }
}

AHBC_DOTNET_MAY_2021/IntroToApis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AHBC_DOTNET_MAY_2021/IntroToApis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroToApis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntroToApis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StarWars" asp-action="Index">Starboy</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tools" asp-action="Index">ToolBoy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IntroToApis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AHBC_DOTNET_MAY_2021/IntroToApis/Views/Tools/Index.cshtml
@model List<ToolsResponseModel>


<h1>Tools Folks</h1>

<table class="table">
    <tbody>
        @foreach (var tool in Model)
        {
            <tr>
                <td>
                    @tool.Name
                </td>
                <td>
                    @tool.Price
                <td>
            </tr>
        }
    </tbody>
</table>