AHBC_DOTNET_MAY_2021/MVCExample/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace MVCExample.Models
{
    public class Book
    {
        public Book(string name)
        {
            Name = name;
        }
        public Book()
        {

        }
        [Required(ErrorMessage = "Yo bro no Id")]
        public int Id { get; set; }

        public string  Name { get; set; }

        public string Author { get; set; }

        //This property doesnt belong but its a cool example
        [EmailAddress]
        public string Email { get; set; }
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Models/Calculator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCExample.Models
{
    public class Calculator
    {
        public int  Num1 { get; set; }
        public int  Num2 { get; set; }
        public char  Operation { get; set; }
        public int  Result { get; set; }
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Models/ErrorViewModel.cs
using System;

namespace MVCExample.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Models/LibraryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCExample.Models
{
    public class LibraryViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Book> Books { get; set; }
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using MVCExample.Models;
using MVCExample.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCExample.Controllers
{
    public class CalculatorController : Controller
    {
        private CalculatorService _calculatorService;
        public CalculatorController(CalculatorService calculatorService)
        {
            _calculatorService = calculatorService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Results(string num1, string num2, char operation)
        {
            var result = _calculatorService.GetCalculation(num1, num2, operation);
            ViewBag.Message = result;
            return View("Result");
        }

    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCExample.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCExample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //return View();
            //return Content("This is the stuff");
            //return EmptyResult();
            //Internal Redirect
            //return RedirectToAction("Privacy");
            //External Redirect
            return RedirectToAction("Index", "Calculator");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using MVCExample.Models;
using MVCExample.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCExample.Controllers
{
    public class LibraryController : Controller
    {
        private BookService _bookService;

        public LibraryController(BookService bookService)
        {
            _bookService = bookService;
            
        }
        public IActionResult Index()
        {
            var librayModel = _bookService.CreateLibraryModel();
            
            return View(librayModel);
        }

        [Route("library/returnbook/{id}")]
        public IActionResult ReturnBook(int id)
        {
            return Content($"You have returned a book ID: {id}");
        }

        [Route("library/viewbook/{id}")]
        public IActionResult ViewBook(int id)
        {
            //Other ways to pass data aside from model 
            ViewData["LocationId"] = "Detriot, MI";
            ViewBag.LocationId = "Detroit, MI";
            TempData["LocationId"] = "Brooklyn";
            var book = _bookService.Books.FirstOrDefault(x => x.Id == id);
            return View(book);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult FormResult(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            var librayModel = _bookService.CreateLibraryModel();
            _bookService.Books.Add(book);
            return View("index", librayModel);
        }
    }
}

AHBC_DOTNET_MAY_2021/MVCExample/Views/Calculator/Index.cshtml
<form asp-controller="Calculator" asp-action="Results">    <label>num1</label>    <input type="text" name="num1" />    <br>    <input type="radio" name="operation" value="+">    <label for="html">Plus</label>    <br>    <input type="radio" name="operation" value="-">    <label for="html">Minus</label>    <br>    <input type="radio" name="operation" value="*">    <label for="html">Multiply</label>    <br>    <input type="radio" name="operation" value="/">    <label for="html">Divide</label>    <br>    <label>num2</label>    <input type="text" name="num2">    <button>Submit</button></form>

AHBC_DOTNET_MAY_2021/MVCExample/Views/Calculator/Results.cshtml
<p>results homie</p>@{ var data = ViewBag.Message;}<h1>Num1: @data.Num1 </h1><h1>Operation: @data.Operator</h1><h1>Num2: @data.Num2</h1><hr /><h1>Equals: @data.Total</h1><hr /><form asp-controller="Home" asp-action="Index">    <button>Back To Calculator</button></form>

AHBC_DOTNET_MAY_2021/MVCExample/Views/Library/Create.cshtml
@model Book

<h1>Create your Book!</h1>



<form asp-controller="Library" asp-action="FormResult">
    <label asp-for="Name"></label>
    <input asp-for="Name" />

    <label asp-for="Author"></label>
    <input asp-for="Author" />

    <label asp-for="Id"></label>
    <input asp-for="Id" />

    <button type="submit"> Create </button>
</form>

<div class="col-md-3">
    @using (Html.BeginForm("FormResult", "Library"))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Id)
            @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Id)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Author)
            @Html.TextBoxFor(m => m.Author, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email)
        </div>

        <button type="submit" class="btn btn-primary"> Create </button>
    }
</div>

AHBC_DOTNET_MAY_2021/MVCExample/Views/Library/Index.cshtml
@model LibraryViewModel

<h1>Welcome to the @Model.Name</h1>


<h3>Here are the list of books I have :</h3>

@if (Model.Books.Count.Equals(0))
{
    <p>Sorry bro no books available</p>
}
else
{

    @foreach (var book in Model.Books)
    {
        <li>@Html.ActionLink($"{book.Name}", "ViewBook", "Library", new { id = book.Id })</li>
    }
}

<h2>Here is an option to create your own book !</h2>

<p>@Html.ActionLink("Create A Book", "Create", "Library")</p>

AHBC_DOTNET_MAY_2021/MVCExample/Views/Library/ViewBook.cshtml
@model Book

<h1>Here is the info for your book</h1>
<h3>Title : @Model.Name</h3>
<h3>Author : @Model.Author</h3>
<h3>Title : @Model.Id</h3>
<h4>@ViewData["LocationId"]</h4>
<h4>@ViewBag.LocationId</h4>
<h4>@TempData["LocationId"]</h4>

AHBC_DOTNET_MAY_2021/MVCExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCExample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>